# Generated by Django 4.2.7 on 2025-11-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayerroom',
            name='current_turn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
