# Generated by Django 4.2.7 on 2025-11-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_multiplayerroom_current_turn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6)),
                ('player', models.CharField(max_length=50)),
                ('power_type', models.CharField(choices=[('time_freeze', 'Time Freeze'), ('line_blaster', 'Line Blaster'), ('color_bomb', 'Color Bomb'), ('gravity_reverse', 'Gravity Reverse'), ('piece_transformer', 'Piece Transformer'), ('shadow_clone', 'Shadow Clone')], max_length=20)),
                ('used', models.BooleanField(default=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'power_ups',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='allow_spectators',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='spectators',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
