# Generated by Django 4.2.7 on 2025-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_powerup_multiplayerroom_allow_spectators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='powerup',
            name='power_type',
            field=models.CharField(choices=[('add_lines', 'Add Lines to Enemy'), ('speed_up', 'Speed Up Enemy'), ('block_bomb', 'Block Bomb'), ('screen_flip', 'Flip Enemy Screen'), ('blind_attack', 'Blind Enemy'), ('gravity_chaos', 'Gravity Chaos')], max_length=20),
        ),
    ]
